# Generated by Django 4.1.6 on 2023-03-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pending_users_model',
            new_name='All_users_model',
        ),
        migrations.AlterModelTable(
            name='all_users_model',
            table='all_users',
        ),
    ]
