# Generated by Django 4.1.7 on 2023-07-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_logistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users_model',
            name='user_Profile',
            field=models.FileField(upload_to='dataset/'),
        ),
    ]
