# Generated by Django 4.1.7 on 2023-07-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_all_users_model_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users_model',
            name='user_Profile',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='upload_dataset_model',
            name='Dataset',
            field=models.FileField(null=True, upload_to='dataset/'),
        ),
    ]
