# Generated by Django 4.1.7 on 2023-07-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_all_users_model_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistic',
            name='Name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='naive_bayes',
            name='Name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
