# Generated by Django 4.1.7 on 2023-03-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict_details',
            fields=[
                ('predict_id', models.AutoField(primary_key=True, serialize=False)),
                ('Field_1', models.CharField(max_length=60, null=True)),
                ('Field_2', models.CharField(max_length=60, null=True)),
                ('Field_3', models.CharField(max_length=60, null=True)),
                ('Field_4', models.CharField(max_length=60, null=True)),
                ('Field_5', models.CharField(max_length=60, null=True)),
                ('Field_6', models.CharField(max_length=60, null=True)),
                ('Field_7', models.CharField(max_length=60, null=True)),
                ('Field_8', models.CharField(max_length=60, null=True)),
                ('Field_9', models.CharField(max_length=60, null=True)),
                ('Field_10', models.CharField(max_length=60, null=True)),
                ('Field_11', models.CharField(max_length=60, null=True)),
                ('Field_12', models.CharField(max_length=60, null=True)),
            ],
            options={
                'db_table': 'predict_detail',
            },
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='images/')),
                ('Email', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Phone_Number', models.CharField(max_length=10, null=True)),
                ('Password', models.CharField(max_length=15, null=True)),
                ('Date_Time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'user_detail',
            },
        ),
    ]
