# Generated by Django 4.1.7 on 2023-03-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predict_details',
            name='Field_11',
        ),
        migrations.RemoveField(
            model_name='predict_details',
            name='Field_12',
        ),
    ]
