# Generated by Django 4.1.6 on 2023-03-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_predict_details_field_11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='User_Status',
            field=models.CharField(default='pending', max_length=50, null=True),
        ),
    ]
