# Generated by Django 4.1.7 on 2023-03-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_user_details_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='User_Status',
            field=models.CharField(default='pending', max_length=50, null=True),
        ),
    ]
