# Generated by Django 4.1.7 on 2023-03-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_user_details_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='Otp_Num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Otp_Status',
            field=models.CharField(default='pending', max_length=60, null=True),
        ),
    ]
