# Generated by Django 4.1.7 on 2023-03-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='Last_Login_Time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
