# Generated by Django 4.1.7 on 2023-03-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_user_details_last_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Last_Login_Time',
            field=models.TimeField(null=True),
        ),
    ]
