# Generated by Django 4.1.7 on 2023-03-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_user_details_last_login_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='Last_login_Date',
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Last_Login_Time',
            field=models.DateTimeField(null=True),
        ),
    ]
