# Generated by Django 4.1.7 on 2023-03-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_remove_user_details_last_login_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='Last_Login_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Last_Login_Time',
            field=models.TimeField(null=True),
        ),
    ]
