# Generated by Django 4.1.7 on 2023-07-10 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_remove_user_details_no_of_predictions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('Feedback_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Review', models.CharField(max_length=1000)),
                ('Rating', models.CharField(max_length=1000)),
                ('Sentiment', models.CharField(max_length=1000)),
                ('Feedback_Time', models.DateTimeField(auto_now=True)),
                ('Reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user_details')),
            ],
            options={
                'db_table': 'user_feedback',
            },
        ),
    ]
